### ISSUE TITLE
Cellranger-arc - possible stratocumulus versioning issue

### ISSUE THREAD

**Issue by chenebroad** [lilab-bcb/cumulus#415]
We're trying to run Cellranger-ARC, pulling from the 2.0.2-max-cell docker image for our pipeline and encounter an error with stratocumulus (GCP paths removed):

strato cp: error: unrecognized arguments: --backend gs://PATH
Traceback (most recent call last):
File "<stdin>", line 15, in <module>
File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
strato exists --backend gcp gs://PATH
strato cp --backend gcp -m gs://PATH
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['strato', 'exists', '--backend', 'gcp', 'gs://PATH]' returned non-zero exit status 2.

It had previously worked with the previous iteration of the docker image around a month ago, and we noted that this was prior to the change from stratocumulus==0.1.7 -> 0.2.4, it seems like the removal of the --backend flag has caused some issues with our pipeline, is there some component of either the WDL or package that can be altered to accommodate this change?

**Comment by yihming** [comment]
Hi @chenebroad ,

For your case, you may want to switch to the most recent version of the Cellranger workflow, i.e. v2.6.3.


Sincerely,
Yiming

**Comment by yihming** [comment]
I'll close this thread. Please feel free to open it if your issue persists.
